- tests/nuodb_entity_test.py
There was a missing wait which caused occasional test failures.
> Add wait in entity test

- pynuodb/datatype.py
Also includes a transformation of a long if-elif  into a dict that should be more efficient.
> Changes in datatypes to support latest nuodb datatypes

- setup.py
> Fix typo: licence to license

- pynuodb/encodedsession.py
- pynuodb/exception.py
- pynuodb/session.py
- tests/dbapi20.py
Updated EncodedSession, Session and Exception for Python 3.0 compliance while maintaining 2.0 usability. Changes such as xrange to range, StandardError to Exception and minor syntax adjustments were made.
> Python 3.0+ compliance in EncodedSession, Session and Exception

- pynuodb/__init__.py
- pynuodb/crypt.py
- pynuodb/encodedsession.py
- tests/nuodb_connect_test.py
- tests/nuodb_cursor_test.py
- tests/nuodb_executionflow_test.py
- tests/nuodb_globals_test.py
- tests/nuodb_huge_test.py
- tests/nuodb_statement_management_test.py
- tests/nuodb_transaction_test.py
Basic, very minor, code cleanups so the code is more PEP 8 compliant.
> Static code analysis cleanup, PEP 8 normalization in some files.

- .coveragerc
- .gitignore
- .travis.yml
- CONTRIBUTING.rst
- Makefile
- tests/nuodb_cursor_test.py
Add contributing file to detail how to build the project, run coverage tools, etc. Cleanup misc. Add coverage reporting for both HTML output and CLI output. This is ready to have Coveralls run analysis online with detailed online reporting.
> Coverage tool integration, developer documentation, misc cleanup.

- README.rst
- tests/nuodb_stress_test.py
Add badges for project status, and eliminate an unnecessary trailing semicolon.
> Get dependencies status and code health stats.

- LICENSE
- README.rst
- setup.py
Fixes a loss on one of the requests you had, and makes the readme looks fantastic. See my repo page for an example. Fixed license term to include 2015.
> Improve README.

- Makefile
Some minor changes to the Makefile, updated year, set clean to remove files generated through install and testing
> Updated clean after install in the Makefile

- README.rst
More detailed examples for both the SQL and management APIs.
> Better examples

- pynuodb/connection.py
- pynuodb/crypt.py
- pynuodb/encodedsession.py
- pynuodb/entity.py
- pynuodb/protocol.py
- pynuodb/session.py
- pynuodb/util.py
- tests/nuodb_basic_test.py
- tests/nuodb_blob_test.py
Driver is now passing most tests in Python 3, as well updated class declarations for portability
> More compliance for Python 3

- pynuodb/encodedsession.py
- setup.py
- tests/nuodb_basic_test.py
Updated ScaledCount2 handling of negative values and added a test for negative scaledCount2 for better product coverage.
> Updated ScaledCount2 handling of negative values

- tests/nuodb_basic_test.py
In light of recent issues, I have added mores scrupulous testing to small decimal, integer and big integer numeric types.
> Added tests for numeic edge cases

- README.rst
- pynuodb/crypt.py
- pynuodb/cursor.py
- pynuodb/entity.py
- pynuodb/exception.py
- pynuodb/result_set.py
- pynuodb/session.py
- pynuodb/statement.py
Updated python docstrings, mostly for type hinting in the current version of PyCharm IDE.
> Updated Python docstrings

- pynuodb/entity.py
update entity.py Domain.create_description() API to add a param
for the default database options.
update Description.build_create_request to check for None param,
then iterate through options map.
> [DB-13069] create_description, add db-opts param

- .travis.yml
- pynuodb/__init__.py
- tests/dbapi20.py
- tests/dbapi20_tpc.py
- tests/nuodb_basic_test.py
- tests/nuodb_blob_test.py
- tests/nuodb_cursor_test.py
- tests/nuodb_executionflow_test.py
- tests/nuodb_globals_test.py
- tests/nuodb_huge_test.py
- tests/nuodb_transaction_test.py
Two changes:
* Update the unittest calls to not use obsolete functions.
* We don't have access to the size field in descriptions so don't check them.
> Fix tests.

- pynuodb/crypt.py
- pynuodb/entity.py
- pynuodb/session.py
- pynuodb/util.py
Add extended cipher support to the driver
> Add extended cipher support to the driver

- .travis.yml
- pynuodb/connection.py
- pynuodb/encodedsession.py
- pynuodb/session.py
- pynuodb/util.py
- tests/nuodb_connect_test.py
NuoDB RC 4.0 required for this functionality. Not publicly available yet.
> Implement TLS in Python Driver

- pynuodb/session.py
> [DB-27560],[DB-27563] Remove convert hostname to ip addr

- pynuodb/session.py
- pynuodb/util.py
- tests/nuodb_base.py
- tests/nuodb_basic_test.py
- tests/nuodb_entity_test.py
Pass options such as LBPolicy to the admin
I can't test the LBPolicy with the current Travis setup. It works locally.
> use options as attributes

- pynuodb/encodedsession.py
The ResultSet consists of a header (labels for each returned column)
plus some number of rows.  The maximum size of a single "fetch"
operation is 100,000 bytes.  If the header happens to exceed that size
then the fetch operation will always raise an EndOfStream exception.
The protocol for result sets is a little fragile: we send back a row of
data followed by an optional integer.  If the integer is 1 then there is
another row to be read in this same fetch result message.  If the
integer is 0 then there are no more rows to fetch (the ResultSet is
complete).  If the integer is missing completely then there are more
rows to fetch by sending another request to the server.
In the driver we were always assuming there would be the headers plus at
least one row before we ran out of room in the …
> [155] encodedsession: Support ResultSet with a huge header
