nuodb/nuodb-python

- pynuodb/entity.py
Adding live status attribute to Description object. LiveStatus is a new attribute of description messages that's specifically for the MET/UNMET status of a description and its values can be STOPPED, STARTED, ERROR, MET. The Status attribute now is specific to the status in the durable config used during enforcement, and is now limited to STOPPED and STARTED. The live_status parameter in the Description constructor is optional to not break compatibility.
> Changing entity code to get LiveStatus attribute from a description

- tests/mock_tzs.py
This is just so that the tests can run without a ton of import errors on distributions that don't have /etc/timezone. These import errors are preventing whole test suites from running.
> Changing mock_tzs to use /etc/localtime if /etc/timezone doesn't exist

- pynuodb/encodedsession.py
- tests/nuodb_basic_test.py
This is for PB who uses SQLAlchemy, Flask, and Sandman. This resolves one of the SQLAlchemy compliance test suite bugs against NuoDB. In a nutshell, we successfully store 1.000 and the encoded session returns the value, but on decoding we lose information, namely we lose the exp information. Net net, the result seen in the client is "1" rather than "1.000". This fix produces the latter so there is no loss of information round trip with NuoDB.
> Preserve sign, exp, and int for decimal.Decimal results.

- tests/nuodb_basic_test.py
These cover the remaining issues I discovered while rewriting the SQLAlchemy driver. These along with the prior test case written account for 4 of the remaining 8 issues.
Please accept this test case, it has been disabled as you requested per the previous issue. The defects uncovered are documented in the source comments.
> document more test failures with nuodb python protocol

- README.md
- pynuodb/connection.py
- pynuodb/encodedsession.py
In README, the install line has been added `sudo pip install --upgrade pynuodb`, this will resolve issues with an error in `send` 
Added a call to session.close() in encodedsession.send_close(), this will close the socket which is communicating with the database when connection.close() is called.
A little bit of general cleanup of the code as well.
> Addressing bugs

- README.md
- pynuodb/encodedsession.py
- tests/nuodb_stress_test.py
Added 2 new tests to the testing harness 
- Connect 1000 times to the database
- Process 1,000,000 rows from the database
By running these tests using cProfile I determined that a re-ordering of the getValue if / elif block can save time. This new policy first checks most common datatypes such as String, Int, Double.
Before policy in get Value
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2010973    6.398    0.000   17.808    0.000 encodedsession.py:716(getValue)
```
After policy
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2010973    4.284    0.000   14.684    0.000 encodedsession.py:716(getValue)
```
Updated README to reflect PEP 249 compliance
> Stress tests, getValue policy optimization and README update

- pynuodb/connection.py
- pynuodb/cursor.py
- pynuodb/datatype.py
- pynuodb/encodedsession.py
- pynuodb/entity.py
- pynuodb/exception.py
- pynuodb/util.py
- tests/nuodb_entity_test.py
Standard relative imports to avoid possible conflicts with other libraries, and fix the entity test so it does not try to shutdown all databases, only the databases it used.
This fixes: https://github.com/nuodb/nuodb-python/issues/77
> Relative imports and fix unit test.

- README.rst
The old link on the README no longer pointed to a hosted page, updated to our current getting started guide.
> Updated README with live wiki link

- pynuodb/cursor.py
- pynuodb/encodedsession.py
- tests/nuodb_basic_test.py
Moving ScaleCount 1 & 2 out of UUID seems to have fixed some bugs with large NUMERIC and DECIMAL data types. Fixes [Issue 15](https://github.com/nuodb/nuodb-python/issues/25) and JIRA [DB-10835](http://tools/jira/browse/DB-10835)
> Separated UUID and ScaledCount2

- pynuodb/encodedsession.py
- tests/nuodb_basic_test.py
Decimal sequences longer than 9 bytes are now handled by putScaledCount2, before they were sent under the decimal protocol which would cause an invalid utf-8 sequence upon receiving. A few minor Python 3 fixes to putting data were made as well
> Fixed invalid UTF-8 sequence in tests -- all tests passing

- pynuodb/protocol.py
- pynuodb/session.py
- test_requirements.txt
By preserving the type off the wire the driver no longer splices large results sets.
Fixed a code style issue in protocol.py
Updated required python-coveralls version
> Fixed large dataset tests on Python 3

- pynuodb/encodedsession.py
- pynuodb/session.py
For the crypt.py transformation the information must be encoded as latin-1 (else the numeric values will be off when they are encrypted). If the string returns as non ascii we will encode it from utf-8 and decode it to latin-1 to preserve the values before encryption 
putString:(utf-8 to latin-1) -> RC4 Transform:(latin-1) -> send - (bytes) - receive -> RC4 Transform:(latin-1) -> getString:(latin-1 to utf-8).
Also made some preemptive changes for no cipher by changing the authorize function to except
an option cipher type that defaults to RC4
> Added UTF-8 Support over the wire for python 3+

- pynuodb/encodedsession.py
- tests/nuodb_blob_test.py
Added encode statement to encode latin decrypted string to bytes for large opaque objects 
Removed faulty test which sent binary as a string instead of using the binary object
> Full python 3 support

- pynuodb/connection.py
- pynuodb/encodedsession.py
- tests/nuodb_basic_test.py
The driver now sets clientHost and clientProcessId on database connection. This is to prevent hangups or spoofing.
> Updated driver to set clientHost and clientProcessId

- pynuodb/cursor.py
- pynuodb/encodedsession.py
- pynuodb/result_set.py
- tests/nuodb_cursor_test.py
The driver does not close the ResultSet and with newer versions of nuodb (>=2.1) an OperationalError is thrown similar to: 
```bash
...
raise OperationalError(error_code_string + ': ' + error_string)
pynuodb.exception.OperationalError: 'INVALID_OPERATION: Maximum number of open statements (1000) exceeded'
```
Below is a code snippet that was used to generate the error.
```python
import pynuodb
connection = pynuodb.connect("local", "localhost", "dba", "dba", options={'schema':'platform'})
for i in range(10000):
cursor = connection.cursor()
cursor.execute('select 1 from dual;')
connection.commit()
cursor.close()
```
I believe there was a regression introduced between 2.0.4 and 2.1 that changed the behavior with how we handled ResultSets. 
* Added method close_result_set to encodedsession - …
> [DB-12019] cursor.close() - fails to clear the result set with error thrown with NuoDB version >=2.1

- pynuodb/connection.py
- tests/nuodb_basic_test.py
Since the TE will now handle setting the ClientHost value, we no longer need to set it within the Driver. 
* No longer setting the ClientHost when we create a Connection.
* Explicitly using clientprocessid, clientinfo within the select statement.
* Removed the check for ClientHost test_connection_properties. Since we don't handle the setting of ClientHost value, it seems out of scope for the test to validate a proper ClientHost value was set. For example if the TE was running on some random remote machine there is no way for the driver to actually know beforehand the hostname of that remote machine.
> Driver shouldn't set ClientHost - TE does this now

- pynuodb/cursor.py
- tests/nuodb_executionflow_test.py
Any open resultset for a single cursor object will now be closed implicitly when execute is called.
> [DB-12501] Will implicitly close resultset on execute

- pynuodb/crypt.py
- requirements.txt
- setup.py
I'm thinking of leaving in cryptography as a requirement, because on most systems it will get installed with no issue and it really is so much faster. Add an except on the import, however, to handle the case where we error trying to import cryptography
> Add back old transform as fallback

- pynuodb/session.py
The TLS flags used to be python booleans.
This breaks the {str}:{str} dictionary docstring.
> Make TLS flags strings

- pynuodb/session.py
On MacOS we can see OSError ENOTCONN generated by socket.shutdown().
Ignore these exceptions.
> session: Don't fail shutdown() on spurious errors

- pynuodb/encodedsession.py
Without this we will try to access a None object.
> encodedsession: Check for timeout and throw if detected

- .travis.yml
- DEB packages are no longer produced: switch to TAR
- The download is renamed from nuodb-ce to nuodb.
> Support latest NuoDB releases

- pynuodb/datatype.py
- tests/nuodb_types_test.py
The following types were added:
* binary varying
* timestamp without timezone
Added tests for the different types.
Addresses bug #160
> Add support for missing SQL data types

- pynuodb/crypt.py
- pynuodb/encodedsession.py
- pynuodb/protocol.py
- pynuodb/statement.py
These commits update the client to support these new capabilities:
* SCALEDCOUNT3 : Support newer BIGINT encoding
* Support receiving resultset metadata in the prepare statement results
* Support not autocommitting DDL (there is no change needed in the Python driver)
> Start to increase the support client protocol for the python driver

- pynuodb/connection.py
- pynuodb/encodedsession.py
- pynuodb/session.py
Previously the LAST_COMMIT_INFO feature was only supported at the protocol level: the driver always reported there was no information available about the last commit.
Last commit ensures "read your own writes" capability for committed transactions, even when connections are using different TEs.
Implement an internal structure to store last commit information:
- The information is saved as a process-wide set of data
- Allows the same process to connect to different databases, and to connect to the same database multiple times (to the same or to different TEs).
In order to support Python clients that may use threading with different connections, use a Lock() to access the last commit details.  Python threading doesn't provide reader/writer locks; rather than write one we'll use a simple …
> Add full support for protocol.LAST_COMMIT_INFO (#45)

- pynuodb/calendar.py
- pynuodb/connection.py
- pynuodb/datatype.py
- pynuodb/encodedsession.py
- requirements.txt
- setup.py
- tests/dbapi20.py
- tests/mock_tzs.py
- tests/nuodb_basic_test.py
- tests/nuodb_date_time_test.py
- tests/nuodb_types_test.py
connection:
- Added support for explicit TimeZone connection property
datatype:
- Use Julian calendar for date/datetime before 1582 Oct 4. When the Gregorian calendar was introduced: .  The day after October 4, 1582 (Julian) became October 15, 1582 (Gregorian). .  That 10-day jump is not accounted for in C's calendar logic. .  Julian calendar handles leap years differently. The utc calendar the engine is using understands this the python functions based on C calendar logic do not.
- time.mktime , time.localtime don't support older dates while engine does changing to use calendar above and calculate time, avoid these issues.
- use of datetime + timezone should handle daylight savings times and not be off by an hour.
tests:
-  Use connection property TimeZone to change timezone
-  Support …
> Support timezone-aware datetime objects
